export const CONFIGURATION_OBJECT_PATH_METADATA_KEY = Symbol('CONFIGURATION_METADATA_KEY')
export const CONFIGURATION_OBJECTS_METADATA_KEY = Symbol('CONFIGURATION_OBJECTS_METADATA_KEY')
export const CONFIG_NAME_METADATA_KEY = Symbol('CONFIG_NAME_METADATA_KEY')

export const MODULE_OPTION_TOKEN = Symbol('MODULE_OPTION_TOKEN')
export const MODULE_LOADED_CONFIG_TOKEN = Symbol('MODULE_LOADED_CONFIG_TOKEN')

export const RESET_COLOR = '\x1b[0m'
